services:
  web:
    container_name: registro-audiencias
    build: .
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true